### ISSUE TITLE
AWT.JFrame on server?

### ISSUE THREAD

**Issue by marcin212** [asiekierka/ClassCacheTweakerMC#11]
classcachetweaker-0.1.4.jar
```
 java.lang.reflect.InvocationTargetException
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
       at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
       at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
       at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
       at java.security.AccessController.doPrivileged(Native Method)
       at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
       at java.lang.Class.forName0(Native Method)
       at java.lang.Class.forName(Class.java:264)
       at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
       at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
       at java.awt.Window.initGC(Window.java:475)
       at java.awt.Window.init(Window.java:495)
       at java.awt.Window.<init>(Window.java:537)
       at java.awt.Frame.<init>(Frame.java:420)
       at java.awt.Frame.<init>(Frame.java:385)
       at javax.swing.JFrame.<init>(JFrame.java:189)
       at pl.asie.classcachetweaker.ClassCache.load(ClassCache.java:247)
       at pl.asie.classcachetweaker.ClassCacheTweaker.getLaunchArguments(ClassCacheTweaker.java:112)
       at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
       at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
       ... 6 more
```

**Comment by asiekierka** [comment]
Clear your DISPLAY envvar. I don't think I have a way to reliably detect the server side without depending on at least a subset of Minecraft versions, and I cannot catch AWTErrors.
