### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by Zilacon** [asiekierka/ClassCacheTweakerMC#9]
Is this just drop into the mods folder? Because on your page it says 1.6.4+ and on 1.6.4 it says:

````
05-01 23:19:18 [INFO] [ForgeModLoader] Loading tweak class name pl.asie.classcachetweaker.ClassCacheTweaker
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at nallar.tickthreading.patcher.PatchLauncher.run(PatchLauncher.java:80)
	at nallar.tickthreading.patcher.PatchLauncher.main(PatchLauncher.java:12)
Caused by: java.lang.UnsupportedClassVersionError: pl/asie/classcachetweaker/ClassCacheTweaker : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:166)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	... 6 more
````

Note: I have tried with and without nallar's involvement, same error.

**Comment by asiekierka** [comment]
Java 8 is required.

**Comment by Zilacon** [comment]
MCPC+ only works on Java 7, So how would this run on a 1.6.4 modded server?

**Comment by asiekierka** [comment]
You could not use MCPC+, as there exists a Forge server for 1.6.4.

Besides, I am pretty sure that even if you got this mod to run on MCPC+, the server would explode. Or something.

**Comment by Zilacon** [comment]
Right but not a Forge+Bukkit server.

**Comment by asiekierka** [comment]
I never said I support Forge+Bukkit servers, I'm afraid... and they will not be supported.
